BEGIN;

ALTER TABLE ships
ADD COLUMN IF NOT EXISTS name VARCHAR(80) NOT NULL DEFAULT 'Ares Explorer';

ALTER TABLE ships
ADD COLUMN IF NOT EXISTS level INTEGER NOT NULL DEFAULT 1;

ALTER TABLE ships
ADD COLUMN IF NOT EXISTS energy_current INTEGER NOT NULL DEFAULT 100;

ALTER TABLE ships
ADD COLUMN IF NOT EXISTS energy_max INTEGER NOT NULL DEFAULT 100;

ALTER TABLE ships
ADD COLUMN IF NOT EXISTS shield_current INTEGER NOT NULL DEFAULT 100;

ALTER TABLE ships
ADD COLUMN IF NOT EXISTS shield_max INTEGER NOT NULL DEFAULT 100;

ALTER TABLE ships
ADD COLUMN IF NOT EXISTS hull_current INTEGER NOT NULL DEFAULT 500;

ALTER TABLE ships
ADD COLUMN IF NOT EXISTS hull_max INTEGER NOT NULL DEFAULT 500;

ALTER TABLE ships
ADD COLUMN IF NOT EXISTS cargo_capacity INTEGER NOT NULL DEFAULT 1000;

ALTER TABLE ships
ADD COLUMN IF NOT EXISTS extractor_level INTEGER NOT NULL DEFAULT 1;

ALTER TABLE ships
ADD COLUMN IF NOT EXISTS weapon_slots INTEGER NOT NULL DEFAULT 2;

ALTER TABLE ships
ADD COLUMN IF NOT EXISTS crew_slots INTEGER NOT NULL DEFAULT 4;

COMMIT;